entorno/Proyecto 1/applications/departamento/urls.py
from django.urls import path
from . import views

app_name = 'departamento_app'

urlpatterns = [
    path('departamentos/', views.Departamentos.as_view(), name='departamentos'),
    path('empleado-departamento/', views.EmpleadoDepartamento.as_view(), name='empleado-departamento'),
]

entorno/Proyecto 1/applications/empleados/urls.py
from django.urls import path
from . import views

app_name = 'empleados_app'

urlpatterns = [
    path('', views.InicioView.as_view(), name='inicio'),
    path('Inicio/', views.InicioView.as_view(), name='inicio'),
    path('listar-empleados/', views.ListAll.as_view(), name='listar-empleados'),
    path('empleado/<int:pk>/', views.ListEmployee.as_view(), name='empleado-detail'),
    path('administrar/', views.EmployeeAdmin.as_view(), name='empleados-admin'),

    path('listar-por-area/<shor_name>/', views.ListByArea.as_view(), name='empleados-area'),
    path('listar-por-trabajo/<job>/', views.ListByJob.as_view()),
    path('lista-por-palabra/', views.ListByKword.as_view()),
    path('lista-por-habilidad/<int:pk>/', views.ListBySkill.as_view()),
    path('registrar-empleado/', views.CreateEmployee.as_view(), name='crear-empleado'),
    path('registro-correcto/', views.SuccessCreateTemplate.as_view(), name='register-success'),
    path('editar-empleado/<int:pk>/', views.UpdateEmployee.as_view(), name='editar-empleado'),
    path('edicion-correcta/', views.SuccessEditTemplate.as_view(), name='update-success'),
    path('eliminar-empleado/<int:pk>/', views.DeleteEmployee.as_view(), name='eliminar-empleado'),
    path('eliminado-exitoso/', views.SuccessDeleteTemplate.as_view(), name='delete-success'),
]

entorno/Proyecto 1/empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('', include('applications.empleados.urls')),
    path('', include('applications.departamento.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

entorno/Proyecto 1/templates/includes/header.html
<div class="top-bar">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text">Empleados</li>
      <li><a href="{% url "empleados_app:listar-empleados" %}">Listar</a></li>
      <li><a href="{% url "departamento_app:departamentos" %}">Departamentos</a></li>
      <li><a href="{% url "empleados_app:empleados-admin" %}">Administrar</a></li>
      <li><a href="{% url "departamento_app:empleado-departamento" %}">Nuevo Departamento</a></li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <li><input type="search" placeholder="Buscar empleado..." /></li>
      <li><a href="{% url "empleados_app:crear-empleado" %}" type="button" class="button">Registrar Nuevo</a></li>
    </ul>
  </div>
</div>