entorno/Proyecto 1/applications/empleados/urls.py
from django.urls import path
from . import views

app_name = 'empleados_app'

urlpatterns = [
    path('', views.InicioView.as_view(), name='inicio'),
    path('Inicio/', views.InicioView.as_view(), name='inicio'),
    path('listar-empleados/', views.ListAll.as_view(), name='listar-empleados'),
    path('empleado/<int:pk>/', views.ListEmployee.as_view(), name='empleado-detail'),
    path('administrar/', views.EmployeeAdmin.as_view(), name='empleados-admin'),

    path('listar-por-area/<shor_name>/', views.ListByArea.as_view(), name='empleados-area'),
    path('listar-por-trabajo/<job>/', views.ListByJob.as_view()),
    path('lista-por-palabra/', views.ListByKword.as_view()),
    path('lista-por-habilidad/<int:pk>/', views.ListBySkill.as_view()),
    path('registrar-empleado/', views.CreateEmployee.as_view(), name='crear-empleado'),
    path('registro-correcto/', views.SuccessCreateTemplate.as_view(), name='register-success'),
    path('editar-empleado/<int:pk>/', views.UpdateEmployee.as_view(), name='editar-empleado'),
    path('edicion-correcta/', views.SuccessEditTemplate.as_view(), name='update-success'),
    path('eliminar-empleado/<int:pk>/', views.DeleteEmployee.as_view(), name='eliminar-empleado'),
    path('eliminado-exitoso/', views.SuccessDeleteTemplate.as_view(), name='delete-success'),
]

entorno/Proyecto 1/empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('', include('applications.empleados.urls')),
    path('', include('applications.departamento.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

entorno/Proyecto 1/applications/empleados/models.py
from django.db import models
from applications.departamento.models import Departamento
from ckeditor.fields import RichTextField

# Create your models here.
class Habilidades(models.Model):
    habilidad = models.CharField(verbose_name='Habilidades', max_length=50)

    class Meta:
        verbose_name = 'Habilidad'
        verbose_name_plural = 'Habilidades'

    def __str__(self):
        return f"{self.id}. {self.habilidad}"

JOB_CHOICES = (
    ('0', 'Contador'),
    ('1', 'Administrador'),
    ('2', 'Economista'),
    ('3', 'Otro')
)

class Empleado(models.Model):
    first_name = models.CharField(verbose_name='Nombres', max_length=60)
    last_name = models.CharField(verbose_name='Apellidos', max_length=60)
    full_name = models.CharField(verbose_name='Nombre Completo', max_length=120, blank=True)
    job = models.CharField(verbose_name='Trabajo', max_length=1, choices=JOB_CHOICES)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    habilidades = models.ManyToManyField(Habilidades)
    avatar = models.ImageField(verbose_name='Imagen', upload_to='empleados', blank=True, null=True)
    hoja_vida = RichTextField(default=True)

    class Meta:
        verbose_name = 'Empleado'
        verbose_name_plural = 'Empleados'
        # Puedo ordenar tanto en views.py como en models.py


    def __str__(self):
        return f"{self.id}. {self.first_name} {self.last_name}"

entorno/Proyecto 1/applications/empleados/forms.py
from django import forms
from .models import Empleado

class EmpleadoForm(forms.ModelForm):

    class Meta:
        model = Empleado
        fields = [
            'first_name', 
            'last_name', 
            'job', 
            'departamento',
            'habilidades',
            'avatar',
        ]

        widgets = {
            'habilidades': forms.CheckboxSelectMultiple()
        }

entorno/Proyecto 1/applications/empleados/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, TemplateView, UpdateView, DeleteView
from .models import Empleado
from .forms import EmpleadoForm


# Create your views here.

class InicioView(TemplateView):
    template_name = 'inicio.html'

# 1. Listar todos los empleados del modelo
class ListAll(ListView):
    template_name = 'empleados/list_all.html'
    ordering = ('id') # Puedo ordenar tanto en views.py como en models.py
    paginate_by = 4

    def get_queryset(self):
        palabra_clave = self.request.GET.get("kword", '')
        lista = Empleado.objects.filter(
            full_name__icontains=palabra_clave,
        )
        print (lista)
        return lista

class ListEmployee(DetailView):
    model = Empleado
    template_name = 'empleados/empleado.html'

# 2. Listar los empleados que pertenecen a un area de trabajo
class ListByArea(ListView):
    template_name = 'empleados/list-area.html'
    ordering = ('id')
    context_object_name = 'empleados'
    #queryset = Empleado.objects.filter(departamento__shor_name='Contaduría') # Filtrar datos por queryset -- No tan recomendada --

    # Filtar datos interactuando con la URL del navegador
    def get_queryset(self):
        
        area = self.kwargs['shor_name']
        lista = Empleado.objects.filter(departamento__shor_name=area)
        return lista

# 3. Listar empleados por trabajo
class ListByJob(ListView):
    template_name = 'empleados/list-job.html'
    ordering = ('-id')

    # Filtrar datos utilizando el metodo GET mediante la URL
    def get_queryset(self):

        job = self.kwargs['job'] # Acceder a los JOB_CHOICES mediante el id del campo: job
        lista = Empleado.objects.filter(job=job)
        return lista

# 4. Listar empleados por palabra clave
class ListByKword(ListView):
    template_name = 'empleados/list-by-kword.html'
    context_object_name = 'empleados'

    def get_queryset(self):

        palabra_clave = self.request.GET.get('kword')
        lista = Empleado.objects.filter(first_name=palabra_clave)
        print (lista)
        return lista

class ListBySkill(DetailView):
    model = Empleado
    template_name = 'empleados/list-by-skill.html'
    context_object_name = 'empleado'


class EmployeeAdmin(ListView):
    model = Empleado
    template_name = 'empleados/admin-list.html'
    context_object_name = 'empleados'
    paginate_by = 10
    ordering = ('id')


class CreateEmployee(CreateView):
    model = Empleado
    template_name = 'empleados/create-employee.html'
    form_class = EmpleadoForm
    success_url = reverse_lazy('empleados_app:empleados-admin')

    def form_valid(self, form):

        empleado = form.save()
        empleado.full_name = f"{empleado.first_name} {empleado.last_name}"
        empleado.save()
        return super(CreateEmployee, self).form_valid(form)

class SuccessCreateTemplate(TemplateView):
    template_name = 'empleados/success.html'

class UpdateEmployee(UpdateView):
    model = Empleado
    template_name = 'empleados/editar-empleado.html'
    fields = ['first_name', 'last_name', 'job', 'departamento', 'habilidades',]
    success_url = reverse_lazy('empleados_app:empleados-admin')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        print('----- Metodo POST -------')
        print(request.POST) # Interceptar valores desde la URL con el metodo post antes de que sean enviados y validados
        print('Con el metodo post estoy tomando el valor del campo first_name de mi BD:', request.POST['first_name'])
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        print('---------- Metodo form_valid ---------------')
        print('Se ejecuta despues del metodo post')
        return super().form_valid(form)

class SuccessEditTemplate(TemplateView):
    template_name = 'empleados/success-edit.html'

class DeleteEmployee(DeleteView):
    model = Empleado
    template_name = 'empleados/delete-empleado.html'
    success_url = reverse_lazy('empleados_app:empleados-admin')

class SuccessDeleteTemplate(TemplateView):
    template_name = 'empleados/success-delete.html'

entorno/Proyecto 1/templates/empleados/admin-list.html
{% extends 'base.html' %}

{% block title %}Administracion{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <div class="cell">
            <br>
            <h1>Administracion de Empleados</h1>
        </div>
        <div class="cell">
            <table>
                <thead>
                  <tr>
                    <th width="100">ID</th>
                    <th width="150">Nombre</th>
                    <th width="150">Apellidos</th>
                    <th width="300">Departamento</th>
                    <th width="100">Acciones</th>
                  </tr>
                </thead>
                <tbody>
                  
                 {% for empleado in empleados %}
                  <tr>
                      <td>{{empleado.id}}</td>
                      <td>{{empleado.first_name}}</td>
                      <td>{{empleado.last_name}}</td>
                      <td>{{empleado.departamento.shor_name}}</td>
                      <td><a href="{% url "empleados_app:editar-empleado" empleado.id %}" class="submit warning button">Editar</a></td>
                      <td><a href="{% url "empleados_app:eliminar-empleado" empleado.id %}" class="submit alert button">Eliminar</a></td>
                  </tr>
                 {% endfor %}
                        
                </tbody>
            </table>
        </div>
            {% if is_paginated %} 
        <div class="cell">
            <nav aria-label="Pagination">
                <ul class="pagination">
                
                {% if page_obj.has_previous %}
                <li class="pagination-previous">
                    <a href="?page={{ page_obj.previous_page_number }}">Atras</a>
                </li>                    
                {% endif %}   
                
                {% for pagina in paginator.page_range %}
                
                {% if pagina == page_obj.number %} 
                   <li class="current"><span class="show-for-sr">You're on page</span> {{pagina}}</li>
                {% else %}
                   <li><a href="?page={{pagina}}">{{pagina}}</a></li>
                {% endif %}
                {% endfor %}
                
                {% if page_obj.has_next %}
                <li class="pagination-next">
                    <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                </li>
                {% endif %}
                    
                </ul>
            </nav>
        </div>
        {% endif %}
    </div>
</div>
{% endblock content %}

entorno/Proyecto 1/templates/empleados/create-employee.html
{% extends 'base.html' %}

{% block title %}Registrar Empleado{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <div class="cell">
            <br>
            <h1>Registrar Empleado</h1>
        </div>
        <form class="grid-x grid-margin-x" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="cell large-6">
                <label>Nombre:
                  {{form.first_name}}
                </label>
              </div>
              <div class="cell large-6">
                <label>Apellidos:
                  {{form.last_name}}
                </label>
            </div>
            <div class="cell large-6">
                <label>Trabajo:
                  {{form.job}}
                </label>
              </div>
              <div class="cell large-6">
                <label>Departamento:
                  {{form.departamento}}
                </label>
            </div>
            <div class="cell large-6">
                <label>Habilidades:
                    {{form.habilidades}}
                </label>
            </div>
            <div class="cell large-6">
                <label>Foto:
                    {{form.avatar}}
                </label>
            </div>
            <div class="cell">
                <button type="submit" class="submit success button">Registrar</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

entorno/Proyecto 1/templates/empleados/delete-empleado.html
{% extends 'base.html' %}

{% block title %}Eliminar Empleado{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <br>
    <div class="cell">
        <h1>Eliminar</h1>
    </div>
    <div class="cell">

<form action="" method="post">
    {% csrf_token %}
    <div class="cell">
        <div class="callout alert">
            <h5>Empleado: {{empleado.first_name}} {{empleado.last_name}}</h5>
            <p>¿Desea eliminar empleado?</p>
          </div>
    </div>
    <div class="cell">
        <button class="alert button" type="submit">Eliminar</a>
    </div>
</form>
    </div>
</div>
{% endblock content %}

entorno/Proyecto 1/templates/empleados/editar-empleado.html
{% extends 'base.html' %}

{% block title %}Editar Empleado{% endblock title %}


{% block content %}
    {% include 'includes/header.html' %}
    <div class="grid-container">
        <br>
        <div class="grid-x">
            <h1 class="cell">Editar Empleado</h1>
            <div class="cell">
                <form class="grid-x grid-margin-x" action="" method="post">
                    {% csrf_token %}
                    <div class="cell large-6">
                        <label>Nombre:
                          {{form.first_name}}
                        </label>
                      </div>
                      <div class="cell large-6">
                        <label>Apellidos:
                          {{form.last_name}}
                        </label>
                      </div>
                      <div class="cell large-6">
                        <label>Trabajo:
                          {{form.job}}
                        </label>
                      </div>
                      <div class="cell large-6">
                        <label>Departamento:
                          {{form.departamento}}
                        </label>
                      </div>
                      <div class="cell large-6">
                        <label>Habilidades:
                          {{form.habilidades}}
                        </label>
                      </div>
                      <div class="cell">
                        <button type="submit" class="submit success button">Actualizar</button>
                      </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

entorno/Proyecto 1/templates/empleados/empleado.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{empleado.first_name}} {{empleado.last_name}}{% endblock title %}

{% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container">
        <div class="grid-x" style="margin: 20px">
            <div class="card" style="width: 300px;">
                <div class="card-divider">
                  <h4>{{empleado.get_job_display}}</h4>
                </div>
                <div class="grid-x align-center">
                    
                    {% if empleado.avatar and empleado.avatar.url%}
                        <p>empleado.avatar: {{ empleado.avatar }}</p>
                        <p>empleado.avatar.url: {{ empleado.avatar.url }}</p>
                        <img width="200" src="{{ empleado.avatar.url }}">
                    {% else %}
                        <img width="200" src="{% static 'img/profile-icon.png' %}">
                    {% endif %}
                        
                </div>
                <div class="card-section">
                  <div class="grid-x" style="text-align: center">
                    <div class="cell">
                        <h1>{{empleado.first_name}} {{empleado.last_name}}</h1>
                    </div>
                    <div class="cell large-6">
                        <p><strong>Trabajo:</strong> {{empleado.get_job_display}}</p>
                    </div>
                    <div class="cell large-6">
                        <p><strong>Departamento:</strong> {{empleado.departamento.shor_name}}</p>
                    </div>
                    <div class="cell large-6">
                        <p><span class="label">Habilidades:</span></p>
                        <ul class="vertical-align">
                            
                            {% for h in empleado.habilidades.all %}
                                <li>{{h.habilidad}}</li>
                            {% endfor %}
                                
                        </ul>
                    </div>
                    <div class="cell">
                        <p><strong>Hoja de Vida:</strong> {{empleado.hoja_vida|safe}}</p>
                    </div>
                </div>
                </div>
              </div>
        </div>
    </div>
{% endblock content %}
    

entorno/Proyecto 1/templates/empleados/list-area.html
{% extends 'base.html' %}

{% block title %}Empleados por Area{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <div class="cell">
            <h1>Listar Empleados por Area</h1>
        </div>
        <div class="cell">
            <hr>
            <table>
                <thead>
                  <tr>
                    <th width="100">ID</th>
                    <th width="150">Nombre</th>
                    <th width="150">Apellidos</th>
                    <th width="300">Departamento</th>
                    <th width="150">Acciones</th>
                  </tr>
                </thead>
                <tbody>
                  
                 {% for empleado in empleados %}
                  <tr>
                      <td>{{empleado.id}}</td>
                      <td>{{empleado.first_name}}</td>
                      <td>{{empleado.last_name}}</td>
                      <td>{{empleado.departamento.shor_name}}</td>
                      <td><a href="{% url "empleados_app:empleado-detail" empleado.id %}" class="submit warning button">Ver</a></td>
                  </tr>
                 {% endfor %}
                        
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock content %}

entorno/Proyecto 1/templates/empleados/list-by-kword.html
<h1>Listar por palabra clave</h1>

<form action="" method="get">
    {% csrf_token %}
    <input type="text" name="kword" id="kword">
    <button type="submit">Buscar</button>
</form>

<h3>Listar resultados</h3>

<ul>
    
    {% for elemento in empleados %}
        <li>{{elemento}}</li>
    {% endfor %}
        
</ul>

entorno/Proyecto 1/templates/empleados/list-by-skill.html
<h1>Lista por habilidad</h1>

    <h2>{{empleado.first_name}} {{empleado.last_name}}</h2>
    <ul>
        
        {% for habilidad in empleado.habilidades.all %}
            <li>{{habilidad}}</li>
        {% endfor %}
            
    </ul>
        
</ul>

entorno/Proyecto 1/templates/empleados/list-job.html
<h1>Listar por Trabajo</h1>

<ul>
    
    {% for name in object_list %}
        <li>{{name}}</li>
    {% endfor %}
        
</ul>

entorno/Proyecto 1/templates/empleados/list_all.html
{% extends 'base.html' %}

{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <br>
    <h1>Lista de Empleados</h1>
    <div class="grid-x">
        <form class="cell grid-x grid-margin-x" method="GET">
            {% csrf_token %}
            <div class="cell large-7">
                <input type="text" name="kword" id="kword" placeholder="Buscar empleado">
            </div>
            <div class="cell large-1">
                <button type="submit" class="submit primary button">Buscar</button>
            </div>
        </form>
        <div class="cell">
            <table>
                <thead>
                  <tr>
                    <th width="100">ID</th>
                    <th width="150">Nombre</th>
                    <th width="150">Apellidos</th>
                    <th width="300">Departamento</th>
                    <th width="150">Acciones</th>
                  </tr>
                </thead>
                <tbody>
                  
                 {% for elemento in page_obj %}
                  <tr>
                      <td>{{elemento.id}}</td>
                      <td>{{elemento.first_name}}</td>
                      <td>{{elemento.last_name}}</td>
                      <td>{{elemento.departamento.shor_name}}</td>
                      <td><a href="{% url "empleados_app:empleado-detail" elemento.id %}" class="submit warning button">Ver</a></td>
                  </tr>
                 {% endfor %}
                        
                </tbody>
            </table>
        </div>

        
        {% if is_paginated %} 
        <div class="cell">
            <nav aria-label="Pagination">
                <ul class="pagination">
                
                {% if page_obj.has_previous %}
                <li class="pagination-previous">
                    <a href="?page={{ page_obj.previous_page_number }}">Atras</a>
                </li>                    
                {% endif %}   
                
                {% for pagina in paginator.page_range %}
                
                {% if pagina == page_obj.number %} 
                   <li class="current"><span class="show-for-sr">You're on page</span> {{pagina}}</li>
                {% else %}
                   <li><a href="?page={{pagina}}">{{pagina}}</a></li>
                {% endif %}
                {% endfor %}
                
                {% if page_obj.has_next %}
                <li class="pagination-next">
                    <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                </li>
                {% endif %}
                    
                </ul>
            </nav>
        </div>
        {% endif %}
            

    </div>

    
</div>
{% endblock content %}
<!--
    <ul>
        {% for elemento in lista %}
        <li>{{elemento}}</li>
        {% endfor %}
        
    </ul>

    <div class="pagination">
        <span class="step-links">
            
            {% if page_obj.has_previous %}
            <a href="?page=1">Primera Página</a>
            <a href="?page={{ page_obj.previous_page_number }}">Anterior</a>
        {% endif %}
        
        <span class="current">
            Página {{page_obj.number}} de {{page_obj.paginator.num_pages}}
        </span>
        
        
        {% if page_obj.has_next %}
        <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
        <a href="?page={{page_obj.paginator.num_pages}}">Ultima Página</a>
        {% endif %}
    </span>
</div>

<div>
    <p>Página actual: {{ page_obj.number }}</p>
    <p>Total de páginas: {{ page_obj.paginator.num_pages }}</p>
    <p>¿Tiene página anterior?: {{ page_obj.has_previous }}</p>
    <p>¿Tiene página siguiente?: {{ page_obj.has_next }}</p>
    
</div>
<!-- Etiquetas de depuración -->
<!--
    <div>
        <h2>Depuración del Contexto</h2>
        <pre>{{ debug_lista }}</pre>
        <pre>{{ lista }}</pre>
        <pre>{{ page_obj }}</pre>
        <pre>{{ paginator }}</pre>
    </div>
    
-->

entorno/Proyecto 1/templates/empleados/success-delete.html
<h1>Empleado eliminado exitosamente</h1>

entorno/Proyecto 1/templates/empleados/success-edit.html
<h1>Empleado actualizado exitosamente</h1>

entorno/Proyecto 1/templates/empleados/success.html
<h1>Se ha creado registrado un empleado correctamente!</h1>