entorno/Proyecto 1/applications/departamento/urls.py
from django.urls import path
from . import views

app_name = 'departamento_app'

urlpatterns = [
    path('departamentos/', views.Departamentos.as_view(), name='departamentos'),
    path('empleado-departamento/', views.EmpleadoDepartamento.as_view(), name='empleado-departamento'),
]

entorno/Proyecto 1/applications/empleados/urls.py
from django.urls import path
from . import views

app_name = 'empleados_app'

urlpatterns = [
    path('', views.InicioView.as_view(), name='inicio'),
    path('Inicio/', views.InicioView.as_view(), name='inicio'),
    path('listar-empleados/', views.ListAll.as_view(), name='listar-empleados'),
    path('empleado/<int:pk>/', views.ListEmployee.as_view(), name='empleado-detail'),
    path('administrar/', views.EmployeeAdmin.as_view(), name='empleados-admin'),

    path('listar-por-area/<shor_name>/', views.ListByArea.as_view(), name='empleados-area'),
    path('listar-por-trabajo/<job>/', views.ListByJob.as_view()),
    path('lista-por-palabra/', views.ListByKword.as_view()),
    path('lista-por-habilidad/<int:pk>/', views.ListBySkill.as_view()),
    path('registrar-empleado/', views.CreateEmployee.as_view(), name='crear-empleado'),
    path('registro-correcto/', views.SuccessCreateTemplate.as_view(), name='register-success'),
    path('editar-empleado/<int:pk>/', views.UpdateEmployee.as_view(), name='editar-empleado'),
    path('edicion-correcta/', views.SuccessEditTemplate.as_view(), name='update-success'),
    path('eliminar-empleado/<int:pk>/', views.DeleteEmployee.as_view(), name='eliminar-empleado'),
    path('eliminado-exitoso/', views.SuccessDeleteTemplate.as_view(), name='delete-success'),
]

entorno/Proyecto 1/empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('', include('applications.empleados.urls')),
    path('', include('applications.departamento.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

entorno/Proyecto 1/applications/departamento/models.py
from django.db import models

# Create your models here.
class Departamento(models.Model):
    name = models.CharField(verbose_name='Nombre', max_length=30) # blank: True: Meter campos no obligatorios.
    shor_name = models.CharField(verbose_name='Nombre corto', max_length=50, unique=True)
    anulate = models.BooleanField(verbose_name='¿Anulado?', default=False)

    class Meta:
        verbose_name = 'Departamento'
        verbose_name_plural = 'Departamentos'
        ordering = ['-id']
        unique_together = ('name', 'shor_name')

    def __str__(self):
        return f'{self.id} - {self.name} - {self.shor_name}'

entorno/Proyecto 1/applications/departamento/forms.py
from django import forms

class NewRegisterForm(forms.Form):
    nombre = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'placeholder':'Nombre del empleado'}))
    apellidos = forms.CharField(max_length=60, widget=forms.TextInput(attrs={'placeholder':'Apellidos del empleado'}))
    departamento = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'placeholder':'Nombre del Departamento'}))
    shorname = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'placeholder':'Abreviatura'}))

    class Meta:
        fields = ('nombre', 'apellidos', 'departamento', 'shorname',)
        widgets = {
            'nombre': forms.TextInput(
                attrs = {
                    'placeholder':'Nombre'
                }
            ),
            'apellidos': forms.TextInput(
                attrs = {
                    'placeholder':'Apellidos'
                }
            )
        }

entorno/Proyecto 1/applications/departamento/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView
from django.views.generic import ListView
from .forms import NewRegisterForm
from applications.empleados.models import Empleado
from .models import Departamento

# Create your views here.
class Departamentos(ListView):
    model = Departamento
    template_name = 'departamento/departamentos.html'
    context_object_name = 'departamentos'

class EmpleadoDepartamento(FormView):
    template_name = 'departamento/empleado-departamento.html'
    form_class = NewRegisterForm
    success_url = '/'

    def form_valid(self, form):
        print('-------------------------')
        # Maneras de recuperar datos desde el formulario

        # Opcion A:
        depa = Departamento(
            name = form.cleaned_data['departamento'],
            shor_name = form.cleaned_data['shorname'],
        )

        depa.save()

        # Opcion B
        nombre = form.cleaned_data['nombre']
        apellido = form.cleaned_data['apellidos']
        Empleado.objects.create(
            first_name = nombre,
            last_name = apellido,
            job = '0',
            departamento = depa,
        )

        return super(EmpleadoDepartamento, self).form_valid(form)
    

entorno/Proyecto 1/templates/departamento/departamentos.html
{% extends 'base.html' %}

{% block title %}Departamentos{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <div class="cell">
            <br>
            <h1>Lista de Departamentos</h1>
        </div>

        <div class="cell">
            <table>
                <tbody>
                
                {% for departamento in departamentos %}
                <tr>
                    <td><strong>{{departamento.name}}</strong></td>
                    <td>{{departamento.shor_name}}</td>
                    <td><a href="{% url "empleados_app:empleados-area" departamento.shor_name %}" class="submit warning button">Ver Departamento</a></td>
                </tr>
                {% endfor %}
                    
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock content %}

entorno/Proyecto 1/templates/departamento/empleado-departamento.html
{% extends 'base.html' %}

{% block title %}Nuevo Departamento{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <div class="cell">
            <br>
            <h1>Registro de Empleado por Departamento</h1>
        </div>
        <form class="grid-x grid-margin-x callout" action="" method="post">
            {% csrf_token %}
            <div class="cell">
                <h3>Datos del Empleado:</h3>
            </div>
            <div class="cell large-6">
                <label>Nombre:
                  {{form.nombre}}
                </label>
              </div>
            <div class="cell large-6">
                <label>Apellidos:
                  {{form.apellidos}}
                </label>
            </div>
            <div class="cell">
                <h3>Datos del Departamento:</h3>
            </div>
            <div class="cell large-6">
                <label>Departamento:
                  {{form.departamento}}
                </label>
              </div>
            <div class="cell large-6">
                <label>Nombre corto del Departamento:
                  {{form.shorname}}
                </label>
            </div>
            <div class="cell">
                <button class="submit success button" type="submit">Guardar</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}